""" Contains filter parameters for our data analysis """

# Pregame Filters
AWAY_TEAM_IDS = []
HOME_TEAM_IDS = []
UNDERDOG_TEAM_IDS = []
FAVORITE_TEAM_IDS = []
MONTHS = []
SEASONS = []
PREGAME_FAVORITE_SPREAD_RANGE = [2.0, 7.0]
PREGAME_FAVORITE_ML_RANGE = []
 
# In game filters
IN_GAME_ELAPSED_SECONDS_RANGE = [720, 900]
IN_GAME_FAVORITE_MARGIN_RANGE = []
IN_GAME_TOTAL_RANGE = []
